### ISSUE TITLE
Can't find generated files

### ISSUE THREAD

**Issue by agueraXneuf** [huextrat/react-native-rate-app#153]
Hi,

After upgrading to react-native 0.78.0, I'm facing an issue with react-native-rate-app. I was working fine before (react-native 0.74.0)

When I run pod install, it also works fine but building the app fails.
I'm not able to find "generated/RNRateAppSpec/RNRateAppSpec.h"
`
.../node_modules/react-native-rate-app/iOS/RateApp.h
.../node_modules/react-native-rate-app/ios/RateApp.h:3:9 'generated/RNRateAppSpec/RNRateAppSpec.h' file not found
`

I also upgrade react-native-rate-app to the latest.

Do you have any idea on how to fix this?

Thanks.

**Comment by huextrat** [comment]
@agueraXneuf Thx for the issue, I've just released v1.2.3 which should fix it

**Comment by nusjeff** [comment]
@huextrat 
xcode 16.1
 "react-native-rate-app": "^1.2.3",
 "react-native": "0.73.5",
Still get this issuse

<img width="1111" alt="Image" src="https://github.com/user-attachments/assets/43268e94-0448-47c3-899b-56aab4c5a4ad" />

**Comment by huextrat** [comment]
@nusjeff This does not seem related to the issue as your issue is on `RCTRequired.h`. Please open a new issue with a reproducible example if you are able to provide it. I'm not able to get this error on my side for now

Some guesses : `Podfile.lock` not up to date, RN version too old (try at least 0.74)
